services:
  webui:
    build:
      context: .
    ports:
      - "3000:8080"
    environment:
      OPENAI_API_BASE_URLS: ${OPENAI_API_BASE_URLS:-http://host.docker.internal:12434/engines/llama.cpp/v1}
      OPENAI_API_KEYS: ${OPENAI_API_KEYS:-docker-model-runner}
      DEFAULT_MODELS: ${DEFAULT_MODELS:-ai/gpt-oss}
      WEBUI_AUTH: ${WEBUI_AUTH:-False}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-data:/app/backend/data

volumes:
  open-webui-data:
